CREATE DATABASE IF NOT EXISTS `` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE ``;

CREATE TABLE IF NOT EXISTS `polls` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`question` text NOT NULL,
	`answer_1` VARCHAR(100) NOT NULL ,
 	`answer_2` VARCHAR(100) NOT NULL ,
 	`answer_3` VARCHAR(100) NOT NULL ,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `poll_answers` (
	`id_a` int(11) NOT NULL AUTO_INCREMENT,
	`poll_id` int(11) NOT NULL,
	`answer` INT(2) NOT NULL ,
	`ip` VARCHAR(20) NULL,
	PRIMARY KEY (`id_a`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

